### ISSUE TITLE
Search autocomplete

### ISSUE THREAD

**Issue by ujum** [zombieFox/nightTab#288] opened 2021-09-27 14:31 UTC
It will be great when typing in search field autocomplete appears (like original google search)

**Comment by zombieFox** [comment] 2021-09-30 07:28
Hi, please complete the feature request form so that I can better understand this request. Do add examples, screenshots or user flows to help describe this feature:


**What kind of feature request is this?**

_Feature improvements – suggestions for something that can make a current feature a bit better._
_Totally new features – ideas for totally new features._

---

**Is your feature request related to a problem? Please describe.**

_A clear and concise description of what the problem is._
_e.g. I'm always frustrated when..._

---

**Describe the solution you'd like**

_A clear and concise description of what you want to happen._

---

**Describe alternatives you've considered**

_A clear and concise description of any alternative solutions or features you've considered._

---

**Additional context**

_Add any other context, links or screenshots about the feature request?_
_Draw some diagrams, link to examples or throw some ASCII art together to show us your vision._

**Comment by ujum** [comment] 2021-09-30 12:26
**Feature improvements**: Search autocomplete

When typing in the search field suggestions will appear

![Screenshot_20210930_152315](https://user-images.githubusercontent.com/11367638/135454182-b02457a2-c264-4690-a44f-be5096b4fb2f.png)


Like native google or other providers search
![Screenshot_20210930_152212](https://user-images.githubusercontent.com/11367638/135454064-639c3be7-3ef7-441d-b003-1da78bc802f8.png)

**Comment by zombieFox** [comment] 2021-10-03 12:06
Thanks for providing more details. This kind of feature would require connecting and sharing data with Google search -- maybe even integration of some sort. This is done by Chrome because it is tied to Google Search.

I'm sure this is not possible. 

I'm afraid this kind of feature is very out of scope of this project.

**Closed by zombieFox** 2021-10-03 12:06 UTC
