### ISSUE TITLE
On FF 79.0b7 this extension defaults at EVERY browser start to the extension's default settings

### ISSUE THREAD

**Issue by PaduaPlay** [zombieFox/nightTab#205] opened 2020-07-14 14:31 UTC
Issue: After the FF 79.0b7 update a few days back, this extension defaults at EVERY browser start to the extension's default settings. Was working fine until the update.

Developer response:  _"Can you help me understand the issue by checking if you have any other extensions which clear data, cookies, local storage when closing Firefox?"_

Yes, there is an extension installed to clean FF at each closing. https://addons.mozilla.org/en-US/firefox/addon/cpd/

1. However, nightTab  was working fine until the update to FF 79.0b7. The above mentioned extension was there before and no new extensions were added.
2. Please clarify : What does nightTab need to remember settings? Cookies / some local storage / both?
3. Can it be set up that after the settings are specified in nightTab - it shows a url that be made the homepage rather than rely on local storage? (for example startpage.com does this and works fine with FF 79b07)

Thank you for a good, functional extension - waiting to start using this extension again when this issue is fixed.

**Comment by Q-out** [comment] 2020-07-15 02:58
The extension you've linked clearly has an option for "Plug-in data", can you confirm that you don't have that option checked?

**Comment by PaduaPlay** [comment] 2020-07-15 05:40
Tried with option for "Plug-in data" unchecked - did not work.

As mentioned, nightTab was working fine until the update to FF 79.0b7. The above mentioned extension was there before (actually, with option for "Plug-in data" CHECKED) and no new extensions were added. 

So, with the option for "Plug-in data" unchecked OR checked - nightTab  resets with every FF restart, on FF 79.0b7.

**Comment by zombieFox** [comment] 2020-07-15 08:47
Hi,

Thanks for reaching out. Sorry you are having issues using nightTab. 
Let's cover some of the facts as we know them and answer some of your questions @PaduaPlay. 

- ClearPrivateData by Ademes does clear all browsers data on Firefox close. 
- nightTab stores all user data in the browser local storage. So ClearPrivateData is the cause of nightTab restoring to default on restart.
- Firefox Beta updated to 79.0b7 on (I believe) 13 July 2020
- The last update to nightTab on Firefox was on 15 June 2020
- I can not find information on when ClearPrivateData was last updated
- The latest nightTab update did not change how the data is saved to the local storage. 

I am unable to test with ClearPrivateData as it does not support my platform (MacOS):
<img width="854" alt="Screenshot 2020-07-15 at 09 15 05" src="https://user-images.githubusercontent.com/7115017/87524173-bea74180-c67f-11ea-9edd-146936042d5b.png">

---

I developed nightTab as a no-database project and as a side effect avoiding privacy concerns as all data the addon saves is  on the client side in the browser. 

Some users have encountered similar issue when using tools which wipe browser data on close. When doing so there is no way to avoid clearing nightTab data too. I am sorry but I don't see how these two addons can work together. 

I believe 79.0**b**7 refers to a beta version of Firefox. Have you tried using the current stable version of Firefox?

**Comment by zombieFox** [comment] 2020-07-15 08:50
> As mentioned, nightTab was working fine until the update to FF 79.0b7. The above mentioned extension was there before (actually, with option for "Plug-in data" CHECKED) and no new extensions were added.

Further, this seems odd, as I do not see why, after an update, Firefox might change what data is marked for deletion by ClearPrivateData.

**Comment by Excigma** [comment] 2020-07-15 09:17
![image](https://user-images.githubusercontent.com/30280397/87527593-75d3a500-c6e0-11ea-932c-5a21391f622f.png)

On Firefox 79.0b7, not able to reproduce

**Comment by Q-out** [comment] 2020-07-15 10:26
Clearing site data in about:preferences#privacy does in fact clear nightTab data as well (78.0.2 Stable). @PaduaPlay, you'll have to uncheck "Offline-Webpage-data" for nightTab to work.

**Comment by PaduaPlay** [comment] 2020-07-15 16:35
_"Some users have encountered similar issue when using tools which wipe browser data on close"_

First of all thank you for your quick responses and attention to the issue raised.
    - and for a good, simple, functional extension.

Since using a privacy tool is likely to be used by most users, if it is possible:
    1. Please consider saving a particular configuration of nightTab as the new default.
    2. This can be in addition to the already available save data option.

If the 'new' default can be saved on the extension itself as the default then as long as the extension is enabled no privacy cleaner can interfere with the working of the extension.

I am not a coder (just a power user) and not sure if the extension's default configuration can be changed like this - but seems like a very logical option.

**Comment by zombieFox** [comment] 2020-07-16 07:38
> First of all thank you for your quick responses and attention to the issue raised. - and for a good, simple, functional extension.

Thanks and welcome!

> 1. Please consider saving a particular configuration of nightTab as the new default.
> 2. This can be in addition to the already available save data option.

An interesting idea however saving any configuration would essentially be the same as what we have right now. The only place to save any configuration or settings is in local storage -- which is what ClearPrivateData is wiping on restart. 

> If the 'new' default can be saved on the extension itself as the default then as long as the extension is enabled no privacy cleaner can interfere with the working of the extension.

That is how nightTab works. When a user makes a change, adds a bookmark, customises the theme, they are creating a "new" default. This new default is saved to local storage. When a new tab is opened, nightTab looks for the settings in the local storage and uses that data to render the page. 

This is what I was referring to when I said I don't see how these two addons can work together. I'm sorry I can't be of more help.

**Comment by PaduaPlay** [comment] 2020-07-16 15:26
_"When a user makes a change, adds a bookmark, customizes the theme, they are creating a "new" default. **This new default is saved to local storage**. "_

1.  The suggestion given was to **save the new default in the extension itself** (inside the xpi) - and not in plugin storage (outside the xpi). This way, no privacy cleaner can impact the user intended functioning of nightTab.

     Just an idea: Maybe store the 'new default' in the nighttab.min.css or have it look up a conf file which is populated with the 'new default'.
OR
2. Is there some way to edit the nighttab.min.css or any other file in the xpi package for a user to change the 'built in default' to what they choose?
       Since there is a already the option to save a config to a .json file..
      Perhaps use the saved .json file to replace something inside the xpi to make the 'new default' the 'built in default'.

This is a good extension, and IMHO better than Tabliss and I would like to be able to use it without compromising on the privacy clean (prefer not to turn off the plug in data clean since there is no way to choose which plug in data to keep / remove).

Thank you.

**Comment by zombieFox** [comment] 2020-07-17 09:52
> The suggestion given was to **save the new default in the extension itself** (inside the xpi) - and not in local / plugin storage (outside the xpi). This way, no privacy cleaner can impact the user intended functioning of nightTab.
> 
> Detail:
> It seems that inside the .xpi of nightTab there is no single directory or .json file where the 'built in default' is stored.
> 
> Is it possible for you to consider modifying the extension to store, in the xpi package, the 'built in default' in a separate .json file (and perhaps name it 'built in default,json') and,

I do not think this is possible. As far as I know, addons and extensions can not write anything to the system or the location where the xpi might be saved/installed. Addons and extensions can only do what a normal website can do, so access browser cache. 

I think Chrome apps, (which [are being discontinued](https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html)) do have access to a, (non standard) method called [requestFileSystem](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestFileSystem). But of course this would [not work for Firefox](https://caniuse.com/#search=requestFileSystem).

Even modifying the files inside the Firefox extensions directory is not allowed as Firefox detects this and deletes the addon, (I am assuming for security reasons).

> Thus the user's new config becomes the 'built in default' - and cleaning the local storage will not affect the user intended behaviour of nightTab - when a new tab is opened, nightTab looks for the settings in the local storage and doesn't find any in local storage (because the cleaner has removed it) and nightTab now renders based on the built in default - which is now, actually, the user's new config.

What you are describing here is forking the project, editing the [bookmarks.js](https://github.com/zombieFox/nightTab/blob/master/src/js/bookmarks.js) and [state.js](https://github.com/zombieFox/nightTab/blob/master/src/js/state.js) files to reflect your bookmarks and settings, [building the project](https://github.com/zombieFox/nightTab#development) locally and installing a unique instance of nightTab manually. Someone else mentioned doing this. Please see issue #171 for more detials.

> This is a good extension, and IMHO better than Tabliss and, if possible, I would like to be able to use it without compromising on the privacy clean (prefer not to turn off the plug in data clean since there is no way to choose which plug in data to keep / remove).

Thanks!

**Comment by zombieFox** [comment] 2020-07-24 12:15
Closing issue as no action will be taken, (there is no way nightTab can work alongside ClearPrivateData).

**Closed by zombieFox** 2020-07-24 12:15 UTC
