### ISSUE TITLE
Feature Request: custom favicon

### ISSUE THREAD

**Issue by mcorossigo** [zombieFox/nightTab#110] opened 2019-11-27 20:21 UTC
Hello @zombieFox 
It would be awesome if you could add an option to customize the favicon of the page.

For reference: https://stackoverflow.com/questions/260857/changing-website-favicon-dynamically

Here a mockup of what I had in mind:

<img width="1280" alt="Schermata 2019-11-27 alle 21 14 02 2" src="https://user-images.githubusercontent.com/36412793/69756590-2ba2b100-115b-11ea-95a6-58a813f780cc.png">

Very similar to how you handle the background, but with an text input instead of a textarea, and using the canvas API you can force a cut/resize so that localStorage doesn't complain.

Also supporting base64 strings would be cool.

**Comment by zombieFox** [comment] 2019-11-29 11:36
Thanks! Looks promising. I feel this should be possible. I'll investigate and see what I can do.

**Comment by ronmurphy** [comment] 2019-12-06 18:46
You can actually add in a one-liner to get the sites actual favicons from google, try this.

`https://www.google.com/s2/favicons?domain=www.bing.com`

**Comment by zombieFox** [comment] 2020-06-15 15:03
This actually got developed on issue ticket #170 
This feature is now on live. ⚡

**Comment by zombieFox** [comment] 2020-06-15 15:11
Been investigating this issue. I does not look like new tab pages support favicons.

**Comment by Jackymancs4** [comment] 2020-06-15 15:23
Copypasting this 
```
(function() {
    var link = document.querySelector("link[rel*='icon']") || document.createElement('link');
    link.type = 'image/x-icon';
    link.rel = 'shortcut icon';
    link.href = 'https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196';
    document.getElementsByTagName('head')[0].appendChild(link);
})();
```

<img width="1280" alt="Schermata 2020-06-15 alle 17 17 26" src="https://user-images.githubusercontent.com/6209647/84675445-8a2f5100-af2c-11ea-9adc-0c2a88a72802.png">

in the Debug Console properly update the favicon (note the stackoverflow icon on the New Tab page), so it seems doable to me, but I may be wrong.

**Comment by zombieFox** [comment] 2020-06-15 15:30
Ah, seems like Firefox does show the favicon but Chrome does not. Nuts.

**Comment by Jackymancs4** [comment] 2020-06-15 15:34
Yes, after a two minutes test (appending the snippets on `nighttab.min.js` and sideloading the extension) I can confirm that it works 100% of the times on Firefox and 0% on Chrome..

So if you decide to implement this (which I hope you'll do because it seems super cool) it would be a Web and Firefox only feat.

**Comment by Excigma** [comment] 2020-06-21 03:00
On Chrome it seems impossible...

https://stackoverflow.com/questions/41494228/adding-a-favicon-to-a-chrome-extension-new-tab-page
https://quick-geek.github.io/answers/590576/index.html

**Comment by zombieFox** [comment] 2021-10-04 07:52
Chrome (and I think Firefox) introduced changes and now have favicon support for start pages. The recent [7.x update](https://github.com/zombieFox/nightTab/releases/tag/v7.3.0) is now out and has a favicon control. This is not supported in every browser but does work in Firefox and Chrome. Marking this as complete.

**Closed by zombieFox** 2021-10-04 07:52 UTC
Labels: feature request, investigate
