### ISSUE TITLE
Bookmark link text does not conform to the primary color

### ISSUE THREAD

**Issue by Fahrenheit** [zombieFox/nightTab#180] opened 2020-05-17 06:20 UTC
After getting this extension for the first time I spent around 30 minutes tweaking and making a setup however there is one issue. As shown in the screenshot, when you hover over the bookmark link text it ends up not theme properly. It should be white as all the other text is with my primary and it's some what ugly as it doesn't match.. Not quite sure what to do about that.
<img width="1680" alt="Screen Shot 2020-05-17 at 2 12 12 AM" src="https://user-images.githubusercontent.com/33299777/82137249-50abde80-97e4-11ea-8305-fe1a9b33a1e5.png">
Here is a second screencap showing my primary color settings if that helps. The main color is set to #d1d1d1
<img width="647" alt="Screen Shot 2020-05-17 at 2 22 10 AM" src="https://user-images.githubusercontent.com/33299777/82137378-58b84e00-97e5-11ea-8c54-cb204a684ecd.png">

PS: I adore this extension.

**Comment by zombieFox** [comment] 2020-05-19 09:14
> PS: I adore this extension.

Thanks! Glad the project is working for you.

> bookmark link text it ends up not theme properly. It should be white as all the other text is with my primary and it's some what ugly as it doesn't match.. Not quite sure what to do about that.

Most of the text in nightTab is based on the Primary Theme Colour. When a colour is selected, the derived colours are used for text to insure strong contrast and readability.

This only works because the background is set to the opposite end of the derived colour spectrum: 
<img width="491" alt="Screenshot 2020-05-19 at 09 59 07" src="https://user-images.githubusercontent.com/7115017/82306942-9f5da200-99b7-11ea-8dc6-796c82837ea1.png">

This means we can aim for at lease AA contrast ratio in most colour selections, eg:
<img width="529" alt="Screenshot 2020-05-19 at 09 56 31" src="https://user-images.githubusercontent.com/7115017/82306655-3bd37480-99b7-11ea-9430-7beb34f08e7f.png">

However the URL text one is instance of text **not** sitting on a derived background colour. It sits on the Accent colour, so the colour contrast can't be controlled the same way. Instead a [special CSS function](https://github.com/zombieFox/nightTab/blob/master/src/css/variables.css#L14) is deriving the appropriate tone, black or white, to be used with the user select Accent Colour. 

I lifted the Accent Colour you used in the screenshot (#fe04c9) and can see the contrast is 6.07:
<img width="552" alt="Screenshot 2020-05-19 at 10 10 00" src="https://user-images.githubusercontent.com/7115017/82307989-0f205c80-99b9-11ea-831a-6e95f5f82f8c.png">

And if I force the colour to white with a quick hack, it is 3.46 (fails):
<img width="541" alt="Screenshot 2020-05-19 at 10 10 26" src="https://user-images.githubusercontent.com/7115017/82308060-2c552b00-99b9-11ea-9ffd-3cca39cc4beb.png">

This is working as intended.

**Comment by zombieFox** [comment] 2020-06-04 07:34
Closing this ticket as this is working as intended.

**Closed by zombieFox** 2020-06-04 07:34 UTC
