### ISSUE TITLE
No auto focus on search field

### ISSUE THREAD

**Issue by uinguzero** [zombieFox/nightTab#32] opened 2019-04-17 11:19 UTC
When opening a new page/tab, the focus is on the address bar instead of the search input

**Comment by zombieFox** [comment] 2019-04-18 10:19
Hi, this is something I have explored already and nightTab now has options to do this (`Options > Search > Focus on load/refresh`). However, if using Chrome it won't allow the Omnibox to loose focus on a new tab initial load. This appears to be an intentional decision by the Chrome team and would require some JS hackery to overcome (opening and closing another url and forcing focus away from the Omnibox). This is not something I do not wish to implement. 

Can you confirm which browser you are using?

**Comment by zombieFox** [comment] 2019-06-07 08:52
Closing this issue as no reply to question -- and the issue is kind of a "won't fix".

**Closed by zombieFox** 2019-06-07 08:52 UTC
