### ISSUE TITLE
how can i actually improve the video quality?

### ISSUE THREAD

**Issue by ducanhpro** [zombieFox/nightTab#374] opened 2022-05-30 14:48 UTC
![image](https://user-images.githubusercontent.com/13045307/171013692-c074feda-404a-4cde-8ea9-e214ffd4fb3d.png)

so i tried to change the video's resolution, change the host,... none seems work. So is there actually a way?

**Comment by zombieFox** [comment] 2022-05-31 16:34
Hi, sorry you are having issues with video quality. Can you share the video URL?

nightTab does not edit or change a video file used as a background. It only links to and displays it on screen. If the video looks blurry please check you have have the Background Video Blur set to 0:

<img width="745" alt="Screenshot 2022-05-31 at 12 32 31" src="https://user-images.githubusercontent.com/7115017/171226885-f686bc9e-3fd5-45fb-8df8-f620815af346.png">

**Comment by zombieFox** [comment] 2022-06-01 15:37
I've had a look at those files. It seems that is just how the videos are made. The image quality seems low. This is not an issue with nightTab I'm afraid. 

If you compare it to some of the videos used in the [nightTab preset themes](https://github.com/zombieFox/nightTabAssets/tree/main/videos) you will see that the elements in the videos are sharp.

**Comment by zombieFox** [comment] 2022-06-02 11:50
Closing issue as this is not caused by nightTab

**Closed by zombieFox** 2022-06-02 11:50 UTC
