### ISSUE TITLE
Header clock alignment bug

### ISSUE THREAD

**Issue by valynor** [zombieFox/nightTab#174] opened 2020-04-14 15:14 UTC
Hey, 

since a couple of versions the clock alignment in the header is buggy: 
when the clock ticks and the numbers change the whole header is moving left or right 1-2 pixels because the different digits apparently take up variable horizontal space.

**Comment by zombieFox** [comment] 2020-04-15 11:48
Hi,

Yes, few updates ago the `min-width` on the clock numbers were removed. This was done for the following reasons:

- Since Theme and Font options were introduced some fonts would render a large space between the clock hours, minutes and seconds due to the `min-width` style.
- So `min-width` is not a scalable solution as any change in font (change in character/number glyph width) could result different space needed for the `min-width` value.
- This means there is no practical way to predict a suitable `min-width` value for the clock numbers.

This means when using a non monospace font the clock may grow or shrink in width at different times. This is working as intended.

**Comment by valynor** [comment] 2020-04-15 18:12
Could you maybe add a font setting just for the clock (or clock+date)? 
The font looks great otherwise (Bookmark Letters etc.) but the left and right shifting is triggering my OCD badly. ;-)

**Comment by zombieFox** [comment] 2020-04-18 08:57
The problem is I'm not sure what this setting would be. If I introduce a control to fix the width of the clock numbers there will always be some font out there which would break the defined fixed width. 

The issue is there is no way to predict what the fixed width should be for any font in the wild.

**Comment by valynor** [comment] 2020-04-18 12:51
I would just change the clock+date to a monospace font - that should fix the problem?

**Comment by zombieFox** [comment] 2020-04-18 13:11
Except if a user decides to change to use a non monospace font.

Just to clarify something, have you tried changing the Display font under `Settings menu > Theme > Fonts > Display` to a monospaced font? That may solve the issue for you.

**Comment by zombieFox** [comment] 2020-04-18 13:32
![Kapture 2020-04-18 at 14 30 37](https://user-images.githubusercontent.com/7115017/79639103-58467c00-8181-11ea-93ae-7bb103e6f7ba.gif)

**Comment by valynor** [comment] 2020-04-18 19:08
Yes, I switched to regular Roboto (it changed the Bookmark Letters too but I guess I can live with that).

**Comment by zombieFox** [comment] 2020-04-23 09:50
The nature of allow the Display and UI font to be changed by the user means nightTab can't impose fixed widths on some elements. The font rendering the clock is working as expected.

Closing this issue as no action can be taken.

**Closed by zombieFox** 2020-04-23 09:50 UTC
