### ISSUE TITLE
Import data files doesn't work with special characters

### ISSUE THREAD

**Issue by siomekziomek** [zombieFox/nightTab#106] opened 2019-11-17 22:45 UTC
Hi there,
Let me congratulate you for making this add-on. I fell in love in it with the first sight.

Unfortunately "Import data" option doesn't work properly on my Firefox 70.0.1. It works fine when you export small file with a few tiles. But when I exported my set of 32 tiles, every time I tried to load it, import option says:

"Not a JSON file. Make sure the selected file came from nightTab."

Even though it definitely is. I didn't change the files name as well. I checked this issue number of times. Even if I export new file, then change accent, and then try to import the file I exported moment ago, the result is the same: "Not a JSON file...".

Keep up the good work :)

**Comment by zombieFox** [comment] 2019-11-19 07:50
Thanks! I'll investigate this. Can you describe your set up please? Do you have any background images applied? 

Would it be possible to share the JSON file you have? This will greatly help investigate this issue.

**Comment by siomekziomek** [comment] 2019-11-22 11:25
Hi,
No, I'm using custom background color. 

Here's the example:
[nightTab backup - 12 16 45 - 22.11.2019.zip](https://github.com/zombieFox/nightTab/files/3879249/nightTab.backup.-.12.16.45.-.22.11.2019.zip)
I made it moment ago. Can't import it as well.

**Comment by zombieFox** [comment] 2019-11-22 17:17
Found the problem, there seems to be a special character in one of your bookmark "name" fields.  The bookmark "Ustaw Lig" has an invisible special character at the end. Which is causing the [isJsonString](https://github.com/zombieFox/nightTab/blob/master/src/js/helper.js#L644) check to return false. This function uses a native Javascript function:`JSON.parse()`. Which is throwing an error because, I guess, that special invisible character isn't allowed in JSON format.

This could have be caused by copying and pasting some text when creating the bookmark. I would suggest removing that bookmark and adding it again by manually typing in the name. 

I'll see if I can't sanitise the bookmark input values on the creation step in an update.

**Comment by siomekziomek** [comment] 2019-11-22 20:15
This special character is "ę" from polish alphabet. I didn't paste it, it's simply alt+e for me ;) It was typed manually.

Yeah, apparently exported files have problem with them. "ę" and "ą" give the same error, while others like "ł" are changed into different characters after importing (WeszBo).

I will restrain from using them for the time being. Thanks for your help and can't wait for 4.0 :)

Cheers

**Comment by zombieFox** [comment] 2019-11-23 09:52
That is good to know! Seems I need to investigate how `JSON.parse()` deals with **intentional** special characters in strings. 😺

**Comment by maxnatt** [comment] 2019-12-22 12:52
The issue can be reproduced with letters from Russian alphabet in bookmark names' as well.

**Comment by SteadyArcticFox** [comment] 2020-02-17 15:24
Chinese characters also have this issue.Only English is well ?

**Comment by zombieFox** [comment] 2020-02-19 23:29
Further investigation, still no joy finding a way to prevent some characters like "ę" causing JSON.parse to return `false`.

A possible solution found here:
https://stackoverflow.com/questions/20856197/remove-non-ascii-character-in-string
Is to use this to remove special characters from the JSON Blob:
`str.replace(/[^\x00-\x7F]/g, "")`

This would allow the JSON to be reimported but without offending characters.

**Comment by zombieFox** [comment] 2020-02-20 12:55
Going with this solution:
https://github.com/zombieFox/nightTab/commit/dc59045cc3d3a75ff5dbbf6e5ce1f309ed83f8e5

**Comment by zombieFox** [comment] 2020-02-24 10:27
A fix is now live for this issue on version [v4.44.0](https://github.com/zombieFox/nightTab/releases/tag/v4.44.0). I've been testing with characters listed in this issue as well as others I could find [on this table](http://www.fileformat.info/info/charset/UTF-8/list.htm). It's working for me.

It would be good to get feedback on this from @siomekziomek and others so I can close this issue. 👍

**Comment by siomekziomek** [comment] 2020-02-24 18:06
Yup, both export and import works with polish characters flawlessly. Great job 👍

**Closed** 2020-02-25 07:29 UTC
Labels: bug, help wanted, investigate

**Comment by MalwareMedusa** [comment] 2023-04-05 07:04
I must say that I liked it a lot, I think it's great in general, except for one thing that makes it almost useless, and I hope they fix it or change it as soon as possible and that is: being a bookmarks extension the most obvious thing is that one can import all the bookmarks you have in Firefox or in another browser, that will accept to import them in a JSON or html file, but it turns out that only allows to import the bookmarks from the same extension? so if you are a new user you are screwed, and then the developer of this extension expects you to import one by one Firefox bookmarks to night tab, which is not only ridiculous but a useless and titanic task! I'm not going to put one by one, if I have about 2000. Anyway, I hope they fix this soon, because the extension is great and looks promising, because if not it's a pity it's only for a few.
