### ISSUE TITLE
Local Background file not loading. (Firefox)

### ISSUE THREAD

**Issue by Munkenmo** [zombieFox/nightTab#69] opened 2019-07-21 22:37 UTC
OS : Windows 10
Firefox : Version 68.0.1
NightTab : 3.61.0 (Addon)

When selecting a local background file, no background appears.  Using a URL works fine.  (I've also exported my backup.json to chrome, and everything works fine there.)

Attached is a copy of the error log that appears in console:

```
nightTab version 3.61.0 init.js:2:9
data version 3.61.0 no need to run update data.js:46:17
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. reset.css:10:29
Unrecognized at-rule or error parsing at-rule ‘@-ms-viewport’. reset.css:15:14
Unknown property ‘text-decoration-skip-ink’.  Declaration dropped. reset.css:61:28
Unknown property ‘speak’.  Declaration dropped. icons.css:16:9
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. icons.css:24:27
Unknown property ‘speak’.  Declaration dropped. form.css:198:9
Unknown pseudo-class or pseudo-element ‘-moz-color-swatch-wrapper’.  Ruleset ignored due to bad selector. form.css:332:21
Ruleset ignored due to bad selector. form.css:428:43
Ruleset ignored due to bad selector. form.css:434:43
Unknown property ‘user-select’.  Declaration dropped. link.css:104:15
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. fontawesome.css:10:27
Stylesheets without CSSOM changes reparsed to check for errors. Refresh the page to also see errors from stylesheets changed from CSSOM and from style attributes.
```

This log was taken after clearing the addon data and closing / reopening firefox.  
I then loaded a local background file, but the error log was the same, (even after closing / reopening)
Loading a URL background also resulted in the same errors, but  does display a background.

**Comment by Q-out** [comment] 2019-07-22 10:49
For the record it only shows these errors when the CSS filter is enabled, it does not show these in the regular Error or Warning filters.
![Screenshot (77)](https://user-images.githubusercontent.com/52709014/61625464-6c178d00-ac98-11e9-9db7-22c9a375a4dc.png)
![Screenshot (78)](https://user-images.githubusercontent.com/52709014/61625457-68840600-ac98-11e9-8923-1015fa7869ea.png)

Also, it is loading the local background for me. But not every image will load. I've tried different resolutions, file sizes, file types, and special characters in file names.

For example these images work on my end:
https://i.imgur.com/HElqzCb.png (Filename: "12 - N5eSKPp", Size: 6.65KB 1920x1080)
https://i.imgur.com/wjS2t49.jpg (Filename: "!@#$%^&()_", Size: 161KB 2560x1707)
https://i.imgur.com/vV1D3Sy.gif (Size: 169KB 800x336) (Does animate)
These don't:
https://i.imgur.com/CnqTrts.png (Size: 795KB 1920x1200)
https://i.imgur.com/QMXZmM5.jpg  (Size: 1052KB 2560x1440)

It might be the Filesize? Highest I was able to load was 665KB. Weird, because Firefox is not supposed to have a [Local Storage limit](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local).

**Comment by zombieFox** [comment] 2019-07-22 14:29
This is interesting, thanks @Munkenmo and @Q-out for the info and details. I've not got a windows machine to test on so this is difficult for me to address.

I've got a VM sort of running and am looking into this. (for the record the background image is rendered as expected on MacOS Chrome and Firefox latest).

Bear with me as I investigate.

**Comment by Munkenmo** [comment] 2019-07-22 21:35
I think Q-out might be onto something with file size.

I took my normal background picture, a 4.9mB png, opened it, used paint.net to save it as a .jpg and lowered quality until it came down to 671kB, and the lower quality version is working.

**Comment by sinankizar** [comment] 2019-07-28 10:27
I have two questions:
How can you set a local image?
If I want to change the background color'how can I do that?
Thanks in advance and sorry to bother the topic :)

**Comment by zombieFox** [comment] 2019-07-28 12:05
@sinankizar nightTab is a stylised new tab page. Sorry, It does not have controls to freely change the main body background colour. This is to maintain the overall look and feel of the project and to keep colour contrast for text. And to make sure the [light/dark theme system](https://github.com/zombieFox/nightTab/blob/master/src/css/variables.css#L120) works as expected.

That being said there are a few ways to make some background colour changes:
- Load an image of a colour using the Background options
- Use the accent colour overlay in the Background options
- Switch the theme to light or dark

I hope that helps.

**Comment by sinankizar** [comment] 2019-07-28 12:26
Thanks for the fast reply. I have managed change the background color with the image that has the color of my choice. Other aspects such as dark theme works flawlessly. It is the best addon for firefox. Thanks for the efforts you put it in.

**Comment by zombieFox** [comment] 2019-07-30 12:24
@sinankizar Bah! I went ahead and added [background colour options](https://github.com/zombieFox/nightTab/commit/cc40feee5e7d7d7220ba2cc172f5b991959f7b76) so if a user knows the risk, can make a custom colour change. It'll be pushed out to the extension/add on in a few days.

**Comment by sinankizar** [comment] 2019-07-30 13:22
You’re the man! When i set an image, the tab bar and the title bar sometimes expanding unexpectedly. If i can reproduce the issue, i will post the details. Thank you so much👍🏻

**Comment by anonymous133** [comment] 2019-08-18 06:35
I have also some Images that don't show when I select them as background image.

Other images from that folder work.

Here are 3 examples that don't show up as background image when selected via the file dialog:

![VzhPD4e](https://user-images.githubusercontent.com/47555412/63221012-23150480-c182-11e9-9d78-ef313f2f3f52.png)

![1xcm5bsohca31](https://user-images.githubusercontent.com/47555412/63221021-37590180-c182-11e9-8899-6252ec9f0d79.png)

![4rryxdzbktn21](https://user-images.githubusercontent.com/47555412/63221027-48097780-c182-11e9-8a00-fe1a8d81a5b3.jpg)

**Comment by zombieFox** [comment] 2019-08-25 21:35
Thank you @anonymous133 for more details. I'm still investigating alternative ways to load local files. This issues is a tough one.

**Comment by zombieFox** [comment] 2021-09-01 09:04
After a lot of investigating and a few project changes, local images was [dropped from the project scope](https://github.com/zombieFox/nightTab/wiki/Local-background-image). Closing this issue as I can't support this feature any more.

**Closed by zombieFox** 2021-09-01 09:04 UTC
Labels: bug, investigate

**Comment by sachicodex** [comment] 2024-10-25 02:33
![dark-abstract-1920x1080-modern-design-sleek-aesthetics-26415](https://github.com/user-attachments/assets/90d20f41-2e37-4212-a37d-8d756735329a)
![dark-abstract-1920x1080-contemporary-design-minimalistic-26417](https://github.com/user-attachments/assets/b6210540-468e-4fa4-aafa-1687596c2700)


These are good.
