### ISSUE TITLE
can't scroll in preferences in Safari

### ISSUE THREAD

**Issue by scottjl** [zombieFox/nightTab#71] opened 2019-07-24 18:13 UTC
Actually you can scroll the preferences, but if the clock is showing seconds it jumps back to the top with the tick of each second. I'm not fast enough to scroll down and untick seconds before it is back at the top.

I realize Safari isn't officially supported, but maybe seconds could be disabled by default unless a fix is found?

Version 3.61.3, Safari 12.1.2.

Update: Actually it doesn't matter if seconds is on or not. I managed to export a config from Chrome and import to Safari successfully. Even without seconds displayed, every second the preferences jumps back to the top, guessing this is during some update loop?

**Comment by zombieFox** [comment] 2019-07-28 13:39
Yes, I've been looking at Safari on and off and this is an issue. However as you've noticed, Safari is not supported by myself/nightTab right now. Mostly because I'm not familiar with how Safari extensions are developed. They don't seem to be similar to Chrome or Firefox (I may be wrong).

A quick test show you are right, the [update events](https://github.com/zombieFox/nightTab/blob/master/src/js/clock.js#L31) in a lot of modules is causing Safari to refresh scrollable areas. This is very unexpected behaviour for `window.setInterval`.

I'm opening this up for other, please help! 🙏

**Comment by scottjl** [comment] 2019-07-28 13:46
yes I know it isn't officially supported. just wanted to note the issue for future support. it seems to work just fine otherwise.

**Comment by zombieFox** [comment] 2020-02-24 11:20
I just ran a test on Safari Version 13.0.2 (15608.2.30.1.1) and aside from some CSS issues (no clip-path support) the scrolling seems to be working. Just letting you know before I close this issue as support for Safari still can't be a priority (especially as the documentation on developing a Safari extension is poor or broken).

**Closed by zombieFox** 2020-02-24 11:20 UTC
Labels: bug, help wanted
