### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by Schanzation** [zombieFox/nightTab#65] opened 2019-07-12 00:31 UTC
Hello! Sorry to open a issue again. But I made a 5 second video of the screen flashing white on opening a new tab. I saw in the commits its fixed but I'm still getting them

https://youtu.be/9SH7PLFLTK8

**Comment by zombieFox** [comment] 2019-07-12 12:04
Hi, thanks for the details and the video. 

The issue is not really "Done", when the previous ticket was closed it was automatically moved to the "Done" column. 

I'm been researching ways to tackle the white flash. Some of the solutions are in the repo but not released to the Chrome/Firefox extensions yet. I release once I have a stable tested build. Which is not ready yet.

The current solution, (found [in the index file](https://github.com/zombieFox/nightTab/blob/master/src/index.html#L2)) works in Chrome but not Firefox. The more I research into it more the more I think it may not be possible to prevent the white flash in Firefox without adding custom userChrome.css overrides. But watch this space. I'll researching to find a better solution.

**Comment by Q-out** [comment] 2019-07-12 15:08
Is the current solution live on the demo (https://zombiefox.github.io/nightTab/)? I still see the flash on both Chrome and FF on there.

I have the aforementioned userchrome.css overrides on FF and I don't usually get white flashes, as you can see [here](https://i.imgur.com/EpfHlCe.mp4). I also have a [Dark Reader extension](https://darkreader.org) for a full dark experience. (I should have disabled that for the video, but even without it I don't get white flashes) 

I get the [White Flash](https://i.imgur.com/xkk7lGh.mp4) on the extension, the demo, as well as local file, all on FF.
With the Dark Reader extension I mentioned the flash is [no longer white](https://i.imgur.com/Rm2pfWM.mp4), but unfortunately, only when loading from the demo or locally, because the extension can't act on protected pages, like ones from another extension.

**Comment by zombieFox** [comment] 2019-07-12 19:22
Whoa, thanks for all the extra information. I'll do some tests with each of those Add Ons. 👍

**Comment by Q-out** [comment] 2019-08-11 14:30
Unfortunately white flash is back on FF (v68 on Win10) with the latest release 3.69.0 (Extension). It started happening again as soon as I updated from 3.61.3 and nothing else has changed.

**Comment by sheldonhull** [comment] 2019-08-13 02:21
The white flash is a long term known issue with Chrome btw. If you find a solution, let me know, but otherwise I wouldn't make this specific to the extension, as I think it's a known issue with Chrome that not many solutions have proven dependable to fix.

**Comment by Q-out** [comment] 2019-08-13 12:33
In some ways, it _is_ specific to the extension. One reason is that I don't see white flash on https://zombiefox.github.io/nightTab/ because it's still on 3.61.0. Another is that there are fixes for the white flash but they don't normally work with extension pages because they're protected pages.

For Chrome & FF there's [DarkReader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) extensions that remove it. For Chrome there's also [WhiteSlash](https://chrome.google.com/webstore/detail/whiteslash-white-backgrou/koiiicglkbcomcplnggedapdhafigbje?hl=en) if you don't want full dark pages (afaik, since I don't use Chrome).

For FF, there's fixes using userchrome.css. [Shadowfox](https://github.com/overdodactyl/ShadowFox) includes all of them so you'll likely never see a white flash with it on. 

None of these work properly on Extension pages though. zombieFox added something in v3.61.x which fixed the white flash issue (at least on FF w/ extension, I didn't check Chrome) but the thing's back with v3.69.0. Also I can't seem to load 3.69.0 as local file so I can't check that.

**Comment by Q-out** [comment] 2019-08-14 09:54
Now instead of flashing white, it flashes with the theme background color or the custom background color that you set in the background settings. That works out wonderfully!

**Comment by Munkenmo** [comment] 2020-02-01 16:10
In firefox I've worked around this by adding the following setting to about:config

ui.systemUsesDarkTheme   

and set it to 1  (Number, 0 is disabled)

**Comment by zombieFox** [comment] 2020-04-18 10:30
I feel I've done as much as I can about this. Closing the issue.

**Closed by zombieFox** 2020-04-18 10:30 UTC
Labels: WIP, help wanted, investigate
