### ISSUE TITLE
The transition from YouTube displays the default page instead of the configured

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [zombieFox/nightTab#164] opened 2020-03-15 01:49 UTC
Hello!

I am using your extension, but ran into a problem.

I installed and configured the extension for myself. Then I added an extension page as my homepage. Now, if I click on the homepage icon in the panel, I will be taken to the extension page that I configured. It looks like this: 
![111](https://user-images.githubusercontent.com/51476127/76693521-7985eb00-665e-11ea-8b5e-e36a16b19959.png)

But I noticed that if I open YouTube (I have not seen such a problem on other sites), then I click on the homepage icon, the default page will open, and not the one I configured.
![222](https://user-images.githubusercontent.com/51476127/76693527-8e627e80-665e-11ea-8f30-66d01bbcc9a9.png)
Why is this happening?

PS. I am using Firefox Nightly 73 and nightTab 4.44.0.

**Comment by Q-out** [comment] 2020-03-15 15:40
Are you using containers or anything like that? Or incognito mode in some way? Anything that clears or temporarily disables cache and/or cookies?

**Comment by Khomyak-sibiryak** [comment] 2020-03-15 23:21
Yes, I use containers and by default YouTube opens in a Google container. I opened another site in a Google container and went through all the steps, but could not repeat the situation. Disabling container expansion solves the problem, but as I said above, the problem is noticeable only on YouTube.

**Comment by Q-out** [comment] 2020-03-16 03:29
I can only offer workarounds, because I don't think this is an issue originating with nightTab.
One would be to backup and restore your nightTab data onto the one that opens in the Google container. You'll have to do this every time you make any changes to your homepage (it'll take 10 seconds tbh), but you'll have no unexpected behaviour otherwise.
Two would be to give nightTab it's own container and force it to open in that. That way it'll always open with the same data, but any site you visit from your homepage might start opening in nightTab container, unless it has its own.

**Comment by zombieFox** [comment] 2020-03-18 13:41
Sorry, I don't know much about containers so I'm not sure I can help. I would follow @Q-out adivce and experiment to see if a workaround can be found.

**Comment by zombieFox** [comment] 2020-06-04 08:42
Closing this issue as I don't think I can do anything to help.

**Closed by zombieFox** 2020-06-04 08:42 UTC
